### ISSUE TITLE
Repo doesn't contain code

### ISSUE THREAD

**Issue by acromondx** [Mobterest/isar-flutter-tutorial#2]
Hey @Mobterest, this repo does not contain the code for the isar tutorials on youtube.

**Comment by ykaito21** [comment]
@acromondx, you can find the code on different branch other than main.
[https://github.com/Mobterest/isar-flutter-tutorial/tree/lesson-17](url)

**Comment by acromondx** [comment]
> @acromondx, you can find the code on different branch other than main. [https://github.com/Mobterest/isar-flutter-tutorial/tree/lesson-17](url)

Great! Thanks @ykaito21
